# VersionTag: 2605.B5.V46.0
# SupportPS5.1: null
# SupportsPS7.6: null
# SupportPS5.1TestedDate: null
# SupportsPS7.6TestedDate: null
# FileRole: Builder
#Requires -Version 5.1
<#
.SYNOPSIS
    Generates the canonical DIRECTORY-TREE.md from the workspace filesystem.
.DESCRIPTION
    Scans C:\PowerShellGUI directory structure and outputs a markdown tree
    to ~README.md/DIRECTORY-TREE.md. All other docs should reference this
    single generated file instead of embedding their own directory trees.
.NOTES
    Author   : The Establishment
    Version  : 2604.B2.V31.0
    Created  : 31st March 2026
    FileRole : Generator
.LINK
    ~README.md/REFERENCE-CONSISTENCY-STANDARD.md
#>
[CmdletBinding()]
param(
    [string]$WorkspacePath
)

if (-not $WorkspacePath) {
    $myDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $WorkspacePath = Split-Path -Parent $myDir
}

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$readmeDir = Join-Path $WorkspacePath '~README.md'
$outPath   = Join-Path $readmeDir 'DIRECTORY-TREE.md'

# Folders to skip entirely
$excludeDirs = @('.git', '.history', '.venv', '__pycache__', 'node_modules', '.vscode')

function Build-Tree {
    param(
        [string]$Path,
        [string]$Prefix = '',
        [int]$MaxDepth = 3,
        [int]$CurrentDepth = 0
    )

    if ($CurrentDepth -ge $MaxDepth) { return @() }

    $items = Get-ChildItem -Path $Path -Force -ErrorAction SilentlyContinue |
        Where-Object { $excludeDirs -notcontains $_.Name } |
        Sort-Object { -not $_.PSIsContainer }, Name

    $lines = @()
    $itemList = @($items)
    for ($i = 0; $i -lt $itemList.Count; $i++) {
        $item = $itemList[$i]
        $isLast = ($i -eq $itemList.Count - 1)
        $connector = if ($isLast) { '└── ' } else { '├── ' }
        $childPrefix = if ($isLast) { '    ' } else { '│   ' }

        if ($item.PSIsContainer) {
            $childCount = @(Get-ChildItem -Path $item.FullName -Force -ErrorAction SilentlyContinue |
                Where-Object { $excludeDirs -notcontains $_.Name }).Count
            $lines += "$Prefix$connector$($item.Name)/  ($childCount items)"
            $lines += Build-Tree -Path $item.FullName -Prefix "$Prefix$childPrefix" -MaxDepth $MaxDepth -CurrentDepth ($CurrentDepth + 1)
        } else {
            $lines += "$Prefix$connector$($item.Name)"
        }
    }
    return $lines
}

Write-Host "[DirectoryTree] Scanning $WorkspacePath ..." -ForegroundColor Cyan

$treeLines = Build-Tree -Path $WorkspacePath -MaxDepth 3
$totalDirs  = @(Get-ChildItem -Path $WorkspacePath -Directory -Recurse -Force -ErrorAction SilentlyContinue | Where-Object { $excludeDirs -notcontains $_.Name }).Count
$totalFiles = @(Get-ChildItem -Path $WorkspacePath -File -Recurse -Force -ErrorAction SilentlyContinue).Count

$versionTag = '2603.B0.v27.0'
$genDate = Get-Date -Format 'yyyy-MM-dd HH:mm'

$output = @()
$output += "<!-- VersionTag: $versionTag -->"
$output += "<!-- VersionBuildHistory: $versionTag  $genDate  (auto-generated by Build-DirectoryTree.ps1) -->"
$output += '<!-- FileRole: Index -->'
$output += ''
$output += '# PowerShellGUI - Directory Tree'
$output += ''
$output += "> **Auto-generated** by ``Build-DirectoryTree.ps1`` on $genDate. Do not edit manually."
$output += "> All documentation should reference this file instead of embedding inline trees."
$output += ''
$output += "**Workspace:** ``C:\PowerShellGUI\``  "
$output += "**Directories:** $totalDirs | **Files:** $totalFiles"
$output += ''
$output += '```'
$output += 'PowerShellGUI/'
$output += ($treeLines -join "`n")
$output += '```'
$output += ''
$output += '---'
$output += "*Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') | Regenerate: ``.\scripts\Build-DirectoryTree.ps1``*"

$content = $output -join "`n"
[System.IO.File]::WriteAllText($outPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "[DirectoryTree] Written: $outPath ($($treeLines.Count) tree lines)" -ForegroundColor Green


<# Outline:
    Stub: describe module/script purpose here.
#>

<# Problems:
    Stub: list known issues here.
#>

<# ToDo:
    Stub: list pending work here.
#>





