# VersionTag: 2607.B6.V53.0
# FileRole: Script
<#
.SYNOPSIS
    Install a git pre-commit hook that runs the SIN scanner against staged PS files.
.DESCRIPTION
    Writes .git/hooks/pre-commit (no extension) which shells out to pwsh and
    runs Invoke-SINPatternScanner.ps1 against every staged .ps1/.psm1/.psd1 file.
    Aborts the commit with non-zero exit if any blocking SIN regression is found.
    Operator can bypass with `git commit --no-verify` (discouraged).
#>
[CmdletBinding()]
param(
    [string]$RepoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path,
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$gitDir = Join-Path $RepoRoot '.git'
if (-not (Test-Path -LiteralPath $gitDir)) {
    throw "Not a git repository: $RepoRoot (no .git folder)"
}
$hooksDir = Join-Path $gitDir 'hooks'
if (-not (Test-Path -LiteralPath $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir | Out-Null
}
$hookPath = Join-Path $hooksDir 'pre-commit'
if ((Test-Path -LiteralPath $hookPath) -and -not $Force) {
    Write-Warning "Pre-commit hook already exists: $hookPath. Use -Force to overwrite."
    return
}

$hookBody = @'
#!/usr/bin/env sh
# VersionTag: 2607.B6.V53.0
# Auto-generated by scripts/Install-PreCommitHook.ps1 -- runs secret scanner, UI event safety scanner, and pre-commit validation gates.
exec pwsh -NoProfile -ExecutionPolicy Bypass -Command "
  Set-StrictMode -Version Latest;
    \$stagedAll = @(git diff --cached --name-only --diff-filter=ACMR);
    if (@(\$stagedAll).Count -eq 0) { exit 0 }
    Write-Host '[pre-commit] Running secret leak scanner on staged files...' -ForegroundColor Cyan;
    & .\scripts\Invoke-SecretLeakScanner.ps1 -IncludeFiles \$stagedAll -FailOnFindings;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    Write-Host '[pre-commit] Running UI event safety scan...' -ForegroundColor Cyan;
    & .\tests\Invoke-UIEventSafetyScan.ps1 -WorkspacePath .;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    Write-Host '[pre-commit] Running reference integrity check...' -ForegroundColor Cyan;
    & .\scripts\Invoke-ReferenceIntegrityCheck.ps1;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    Write-Host '[pre-commit] Validating canonical pipeline paths...' -ForegroundColor Cyan;
    & .\scripts\Invoke-ValidateCanonicalPaths.ps1 -WorkspacePath . -RegistryPath .\config\pipeline-canonical-paths.json -FailOnMissing;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    Write-Host '[pre-commit] Running pipeline continuous refine scan (strict drift gate)...' -ForegroundColor Cyan;
    & .\scripts\Invoke-PipelineContinuousRefine.ps1 -WorkspacePath . -StagedOnly -BaselineProfile staged -BaselineJson .\config\pipeline-refine-baseline-staged.json -FailOnDrift;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    \$staged = @(\$stagedAll | Where-Object { \$_ -match '\.(ps1|psm1|psd1)\$' });
    if (@(\$staged).Count -eq 0) { exit 0 }
    Write-Host '[pre-commit] Running pre-commit validation gates...' -ForegroundColor Cyan;
    if (@(\$staged).Count -gt 0) {
      & .\tests\Invoke-PreCommitValidation.ps1 -WorkspacePath . -AutoRemediateLogDrift -StagedFiles ([string]::Join([Environment]::NewLine, @(\$staged)));
    } else {
      & .\tests\Invoke-PreCommitValidation.ps1 -WorkspacePath . -AutoRemediateLogDrift;
    }
  exit \$LASTEXITCODE
"
'@

# Use UTF8 *without* BOM for shell scripts (BOM breaks /usr/bin/env on git-bash)
[IO.File]::WriteAllText($hookPath, $hookBody, (New-Object System.Text.UTF8Encoding $false))

# Best-effort: mark executable on systems that support it (no-op on NTFS)
try { & git update-index --chmod=+x .git/hooks/pre-commit 2>$null } catch { <# ignore on Windows #> }

Write-Host "Installed pre-commit hook: $hookPath" -ForegroundColor Green
Write-Host "Bypass with: git commit --no-verify  (discouraged)" -ForegroundColor Yellow



