# VersionTag: 2607.B7.V53.0
# FileRole: Script
<#
.SYNOPSIS
    Install git pre-commit (and optional pre-push) hooks that run the SIN scanner.
.DESCRIPTION
    Writes .git/hooks/pre-commit (no extension) which shells out to pwsh and
    runs Invoke-SINPatternScanner.ps1 against every staged .ps1/.psm1/.psd1 file.
    Aborts the commit with non-zero exit if any blocking SIN regression is found.
    Operator can bypass with `git commit --no-verify` (discouraged).

    With -InstallPrePush, also writes .git/hooks/pre-push which runs the full
    Permissive-ratchet scan across the files changed in the push range. This
    closes the `git commit --no-verify` bypass without paying full-scan cost.
.PARAMETER RepoRoot
    Repository root containing the .git folder.
.PARAMETER Force
    Overwrite existing hook files.
.PARAMETER InstallPrePush
    Also install the pre-push ratchet hook.
#>
[CmdletBinding()]
param(
    [string]$RepoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path,
    [switch]$Force,
    [switch]$InstallPrePush
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$gitDir = Join-Path $RepoRoot '.git'
if (-not (Test-Path -LiteralPath $gitDir)) {
    throw "Not a git repository: $RepoRoot (no .git folder)"
}
$hooksDir = Join-Path $gitDir 'hooks'
if (-not (Test-Path -LiteralPath $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir | Out-Null
}
$hookPath = Join-Path $hooksDir 'pre-commit'
if ((Test-Path -LiteralPath $hookPath) -and -not $Force -and -not $InstallPrePush) {
    Write-Warning "Pre-commit hook already exists: $hookPath. Use -Force to overwrite."
    return
}
$writePreCommit = -not ((Test-Path -LiteralPath $hookPath) -and -not $Force)

$hookBody = @'
#!/usr/bin/env sh
# VersionTag: 2607.B7.V53.0
# Auto-generated by scripts/Install-PreCommitHook.ps1 -- runs secret scanner, UI event safety scanner, and pre-commit validation gates.
exec pwsh -NoProfile -ExecutionPolicy Bypass -Command "
  Set-StrictMode -Version Latest;
    \$stagedAll = @(git diff --cached --name-only --diff-filter=ACMR);
    if (@(\$stagedAll).Count -eq 0) { exit 0 }
    Write-Host '[pre-commit] Running secret leak scanner on staged files...' -ForegroundColor Cyan;
    & .\scripts\Invoke-SecretLeakScanner.ps1 -IncludeFiles \$stagedAll -FailOnFindings;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    Write-Host '[pre-commit] Running UI event safety scan...' -ForegroundColor Cyan;
    & .\tests\Invoke-UIEventSafetyScan.ps1 -WorkspacePath .;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    Write-Host '[pre-commit] Running reference integrity check...' -ForegroundColor Cyan;
    & .\scripts\Invoke-ReferenceIntegrityCheck.ps1;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    Write-Host '[pre-commit] Validating canonical pipeline paths...' -ForegroundColor Cyan;
    & .\scripts\Invoke-ValidateCanonicalPaths.ps1 -WorkspacePath . -RegistryPath .\config\pipeline-canonical-paths.json -FailOnMissing;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    Write-Host '[pre-commit] Running pipeline continuous refine scan (strict drift gate)...' -ForegroundColor Cyan;
    & .\scripts\Invoke-PipelineContinuousRefine.ps1 -WorkspacePath . -StagedOnly -BaselineProfile staged -BaselineJson .\config\pipeline-refine-baseline-staged.json -FailOnDrift;
    if (\$LASTEXITCODE -ne 0) { exit \$LASTEXITCODE }
    \$staged = @(\$stagedAll | Where-Object { \$_ -match '\.(ps1|psm1|psd1)\$' });
    if (@(\$staged).Count -eq 0) { exit 0 }
    Write-Host '[pre-commit] Running pre-commit validation gates...' -ForegroundColor Cyan;
    if (@(\$staged).Count -gt 0) {
      & .\tests\Invoke-PreCommitValidation.ps1 -WorkspacePath . -AutoRemediateLogDrift -StagedFiles ([string]::Join([Environment]::NewLine, @(\$staged)));
    } else {
      & .\tests\Invoke-PreCommitValidation.ps1 -WorkspacePath . -AutoRemediateLogDrift;
    }
  exit \$LASTEXITCODE
"
'@

# Use UTF8 *without* BOM for shell scripts (BOM breaks /usr/bin/env on git-bash)
if ($writePreCommit) {
    [IO.File]::WriteAllText($hookPath, $hookBody, (New-Object System.Text.UTF8Encoding $false))

    # Best-effort: mark executable on systems that support it (no-op on NTFS)
    try { & git update-index --chmod=+x .git/hooks/pre-commit 2>$null } catch { <# ignore on Windows #> }

    Write-Host "Installed pre-commit hook: $hookPath" -ForegroundColor Green
    Write-Host "Bypass with: git commit --no-verify  (discouraged)" -ForegroundColor Yellow
}

if ($InstallPrePush) {
        $prePushPath = Join-Path $hooksDir 'pre-push'
        if ((Test-Path -LiteralPath $prePushPath) -and -not $Force) {
                Write-Warning "Pre-push hook already exists: $prePushPath. Use -Force to overwrite."
        } else {
                $prePushBody = @'
#!/usr/bin/env sh
# VersionTag: 2607.B7.V53.0
# Auto-generated by scripts/Install-PreCommitHook.ps1 -- scans the pushed commit range.
remote="$1"
remote_url="$2"
zero="0000000000000000000000000000000000000000"
range_args=""
while IFS=' ' read -r local_ref local_oid remote_ref remote_oid
do
    if [ "$local_oid" = "$zero" ]; then
        continue
    fi
    if [ "$remote_oid" = "$zero" ]; then
        range_args="$range_args $local_oid"
    else
        range_args="$range_args $remote_oid..$local_oid"
    fi
done
if [ -z "$range_args" ]; then
    exit 0
fi
exec pwsh -NoProfile -ExecutionPolicy Bypass -Command "
    Set-StrictMode -Version Latest;
    \\$changed = @(git diff --name-only --diff-filter=ACMR $range_args);
    if (@(\\$changed).Count -eq 0) { exit 0 }
    Write-Host '[pre-push] Running SIN scan on pushed files...' -ForegroundColor Cyan;
    \\$scanFiles = @(\\$changed | Where-Object { \\$_ -match '\\.(ps1|psm1|psd1)$' });
    if (@(\\$scanFiles).Count -gt 0) {
        & .\\tests\\Invoke-SINPatternScanner.ps1 -WorkspacePath . -Runtime Both -IncludeFiles \\$scanFiles -PermissiveRatchet;
        exit \\$LASTEXITCODE
    }
    exit 0
"
'@
                [IO.File]::WriteAllText($prePushPath, $prePushBody, (New-Object System.Text.UTF8Encoding $false))
                try { & git update-index --chmod=+x .git/hooks/pre-push 2>$null } catch { <# ignore on Windows #> }
                Write-Host "Installed pre-push hook: $prePushPath" -ForegroundColor Green
        }
}



