# VersionTag: 2604.B2.V31.0
# VersionBuildHistory:
#   2603.B0.v27.0  2026-03-24 03:28  (deduplicated from 4 entries)
#Requires -Version 5.1

<#
.SYNOPSIS
# --- Structured lifecycle logging ---
if (Get-Command Write-AppLog -ErrorAction SilentlyContinue) {
    Write-AppLog -Message "Started: $($MyInvocation.MyCommand.Name)" -Level 'Info'
}
    Generates a self-contained PowerShell installer script that helps users
    install missing modules, the latest PowerShell version and the latest
    .NET SDK for their operating system.

.DESCRIPTION
    Reads the most recent module-dependency-matrix JSON from ~REPORTS to
    discover missing or version-mismatched modules. Produces a single .ps1
    file in ~DOWNLOADS\INSTALLER-Scripts that the user can run on any
    target machine to remediate gaps.

    The generated script:
      - Installs / updates missing PowerShell modules from PSGallery
      - Detects the current PowerShell version and offers to install the
        latest stable release via winget or direct MSI/PKG download
      - Detects the current .NET SDK version and offers to install the
        latest via winget or the official dotnet-install script
      - Works on Windows, macOS and Linux (best-effort)

.PARAMETER WorkspacePath
    Root of the PowerShell GUI workspace. Defaults to parent of script dir.

.PARAMETER OutputFolder
    Where to write the generated script. Defaults to
    <WorkspacePath>\~DOWNLOADS\INSTALLER-Scripts

.PARAMETER Open
    If set, opens the generated script in the default editor after creation.

.OUTPUTS
    [string] Full path to the generated installer script.
#>

[CmdletBinding()]
param(
    [string]$WorkspacePath,
    [string]$OutputFolder,
    [switch]$Open
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── resolve paths ──────────────────────────────────────────────────
if ([string]::IsNullOrWhiteSpace($WorkspacePath)) {
    $WorkspacePath = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
}
$reportPath = Join-Path $WorkspacePath '~REPORTS'

if ([string]::IsNullOrWhiteSpace($OutputFolder)) {
    $OutputFolder = Join-Path (Join-Path $WorkspacePath '~DOWNLOADS') 'INSTALLER-Scripts'
}
if (-not (Test-Path $OutputFolder)) {
    New-Item -ItemType Directory -Path $OutputFolder -Force | Out-Null
}

# ── locate latest module matrix JSON ───────────────────────────────
$matrixFiles = @(Get-ChildItem -Path $reportPath -Filter 'module-dependency-matrix-*.json' -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notlike '*-pointer*' } |
    Sort-Object Name -Descending)

$missingModules = @()
$mismatchModules = @()

if ($matrixFiles.Count -gt 0) {
    $matrixData = Get-Content $matrixFiles[0].FullName -Raw | ConvertFrom-Json
    foreach ($mod in $matrixData.modules) {
        $name = [string]$mod.module
        if ([string]::IsNullOrWhiteSpace($name)) { continue }
        $status = [string]$mod.status

        if ($status -like 'missing*') {
            $missingModules += [pscustomobject]@{
                Name            = $name
                RequiredVersion = if ($mod.requiredVersion) { [string]$mod.requiredVersion } else { $null }
                MinimumVersion  = if ($mod.minimumVersion)  { [string]$mod.minimumVersion }  else { $null }
            }
        } elseif ($status -like 'installed-*' -and $status -notlike '*workspace*') {
            $mismatchModules += [pscustomobject]@{
                Name            = $name
                RequiredVersion = if ($mod.requiredVersion) { [string]$mod.requiredVersion } else { $null }
                MinimumVersion  = if ($mod.minimumVersion)  { [string]$mod.minimumVersion }  else { $null }
                Installed       = if ($mod.installedVersion) { [string]$mod.installedVersion } else { 'unknown' }
                Status          = $status
            }
        }
    }
    Write-Host ("Module matrix loaded: {0} missing, {1} mismatched" -f $missingModules.Count, $mismatchModules.Count)
} else {
    Write-Warning "No module-dependency-matrix JSON found in $reportPath -- module section will be empty."
}

# ── build the installer script body ───────────────────────────────

$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$outFile   = Join-Path $OutputFolder "Install-Environment-$timestamp.ps1"

$sb = [System.Text.StringBuilder]::new(16384)

# --- header ---
[void]$sb.AppendLine(@'
#Requires -Version 5.1
<#
.SYNOPSIS
    Environment installer -- missing modules, latest PowerShell & .NET SDK.
    Auto-generated by New-InstallerScript.ps1.

.DESCRIPTION
    Run this script on the target machine (elevated recommended) to:
      1. Install missing PowerShell modules from PSGallery
      2. Upgrade to the latest stable PowerShell 7 release
      3. Install / upgrade the latest .NET SDK

    Supports Windows, macOS and Linux.
    All installs use CurrentUser scope where possible.

.PARAMETER WhatIf
    Preview actions without making changes.
#>

[CmdletBinding(SupportsShouldProcess)]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

$isAdmin = $false
if ($PSVersionTable.Platform -ne 'Unix') {
    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)
}

Write-Host ''
Write-Host '╔══════════════════════════════════════════════════════════════╗' -ForegroundColor Cyan
Write-Host '║      ENVIRONMENT INSTALLER  --  PowerShellGUI Project       ║' -ForegroundColor Cyan
Write-Host '╚══════════════════════════════════════════════════════════════╝' -ForegroundColor Cyan
Write-Host ''
'@)

[void]$sb.AppendLine(@'
Write-Host ("Generated : {0}" -f $MyInvocation.MyCommand.Path) -ForegroundColor DarkGray
Write-Host ("Running as: {0}  Admin: {1}" -f $env:USERNAME, $isAdmin) -ForegroundColor DarkGray
Write-Host ("OS        : {0}" -f [System.Runtime.InteropServices.RuntimeInformation]::OSDescription) -ForegroundColor DarkGray
Write-Host ("PS Version: {0}" -f $PSVersionTable.PSVersion) -ForegroundColor DarkGray
Write-Host ''
'@)

# --- Section 1: Modules ---
[void]$sb.AppendLine(@'
# ════════════════════════════════════════════════════════════════════
# SECTION 1 -- MISSING / MISMATCHED POWERSHELL MODULES
# ════════════════════════════════════════════════════════════════════
Write-Host '── Section 1: PowerShell Modules ──' -ForegroundColor Yellow
Write-Host ''

function Install-RequiredModule {
    param(
        [string]$Name,
        [string]$RequiredVersion,
        [string]$MinimumVersion
    )

    $existing = Get-Module -ListAvailable -Name $Name -ErrorAction SilentlyContinue |
        Sort-Object Version -Descending | Select-Object -First 1

    if ($existing) {
        $needsUpdate = $false
        if ($RequiredVersion) {
            try { if ([version]$existing.Version -ne [version]$RequiredVersion) { $needsUpdate = $true } } catch { $needsUpdate = $true }
        } elseif ($MinimumVersion) {
            try { if ([version]$existing.Version -lt [version]$MinimumVersion) { $needsUpdate = $true } } catch { $needsUpdate = $true }
        }
        if (-not $needsUpdate) {
            Write-Host "  OK : $Name ($($existing.Version))" -ForegroundColor Green
            return
        }
        Write-Host "  UPDATE: $Name installed=$($existing.Version)" -ForegroundColor Yellow -NoNewline
    } else {
        Write-Host "  INSTALL: $Name" -ForegroundColor Magenta -NoNewline
    }

    $installParams = @{ Name = $Name; Scope = 'CurrentUser'; Force = $true; ErrorAction = 'Stop' }
    if ($RequiredVersion) { $installParams['RequiredVersion'] = $RequiredVersion }
    elseif ($MinimumVersion) { $installParams['MinimumVersion'] = $MinimumVersion }

    if ($PSCmdlet.ShouldProcess($Name, 'Install-Module')) {
        try {
            Install-Module @installParams
            Write-Host " -> Done" -ForegroundColor Green
        } catch {
            Write-Host " -> FAILED: $($_.Exception.Message)" -ForegroundColor Red
        }
    } else {
        Write-Host " [WhatIf]" -ForegroundColor DarkYellow
    }
}

'@)

# Emit individual module install calls
if ($missingModules.Count -gt 0 -or $mismatchModules.Count -gt 0) {
    [void]$sb.AppendLine("# --- Missing modules ($($missingModules.Count)) ---")
    foreach ($m in $missingModules) {
        $reqArg = if ($m.RequiredVersion) { " -RequiredVersion '$($m.RequiredVersion)'" } else { '' }
        $minArg = if ($m.MinimumVersion)  { " -MinimumVersion '$($m.MinimumVersion)'" }   else { '' }
        [void]$sb.AppendLine("Install-RequiredModule -Name '$($m.Name)'$reqArg$minArg")
    }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("# --- Mismatched modules ($($mismatchModules.Count)) ---")
    foreach ($m in $mismatchModules) {
        $reqArg = if ($m.RequiredVersion) { " -RequiredVersion '$($m.RequiredVersion)'" } else { '' }
        $minArg = if ($m.MinimumVersion)  { " -MinimumVersion '$($m.MinimumVersion)'" }   else { '' }
        [void]$sb.AppendLine("# Status: $($m.Status)  Installed: $($m.Installed)")
        [void]$sb.AppendLine("Install-RequiredModule -Name '$($m.Name)'$reqArg$minArg")
    }
} else {
    [void]$sb.AppendLine("Write-Host '  No missing or mismatched modules detected.' -ForegroundColor Green")
}

[void]$sb.AppendLine('')

# --- Section 2: Latest PowerShell ---
[void]$sb.AppendLine(@'

# ════════════════════════════════════════════════════════════════════
# SECTION 2 -- LATEST POWERSHELL
# ════════════════════════════════════════════════════════════════════
Write-Host ''
Write-Host '── Section 2: PowerShell Version ──' -ForegroundColor Yellow
Write-Host ''

function Update-PowerShellVersion {
    $current = $PSVersionTable.PSVersion
    Write-Host "  Current PowerShell: $current" -ForegroundColor Cyan

    # Try winget first (Windows)
    $hasWinget = $null -ne (Get-Command winget -ErrorAction SilentlyContinue)

    if ($hasWinget) {
        Write-Host "  Checking winget for latest PowerShell..." -ForegroundColor DarkGray
        try {
            $listOutput = winget list --id Microsoft.PowerShell --accept-source-agreements 2>&1 | Out-String
            $upgradeOutput = winget upgrade --id Microsoft.PowerShell --accept-source-agreements --accept-package-agreements 2>&1 | Out-String

            if ($upgradeOutput -match 'No applicable update found' -or $upgradeOutput -match 'No installed package found') {
                # Not installed via winget -- try install
                if ($PSCmdlet.ShouldProcess('PowerShell 7 (winget)', 'Install')) {
                    Write-Host "  Installing PowerShell via winget..." -ForegroundColor Yellow
                    winget install --id Microsoft.PowerShell --source winget --accept-source-agreements --accept-package-agreements
                    Write-Host "  PowerShell install initiated." -ForegroundColor Green
                } else {
                    Write-Host "  [WhatIf] Would install PowerShell via winget" -ForegroundColor DarkYellow
                }
            } elseif ($upgradeOutput -match 'Successfully installed' -or $upgradeOutput -match 'already installed') {
                Write-Host "  PowerShell is up to date via winget." -ForegroundColor Green
            } else {
                if ($PSCmdlet.ShouldProcess('PowerShell 7 (winget)', 'Upgrade')) {
                    Write-Host "  Upgrading PowerShell via winget..." -ForegroundColor Yellow
                    winget upgrade --id Microsoft.PowerShell --source winget --accept-source-agreements --accept-package-agreements
                    Write-Host "  Upgrade complete." -ForegroundColor Green
                } else {
                    Write-Host "  [WhatIf] Would upgrade PowerShell via winget" -ForegroundColor DarkYellow
                }
            }
            return
        } catch {
            Write-Warning "  winget method failed: $($_.Exception.Message)"
        }
    }

    # Fallback: direct install script from GitHub
    if ($PSVersionTable.Platform -eq 'Unix') {
        Write-Host "  Linux/macOS: use your package manager or https://aka.ms/install-powershell.sh" -ForegroundColor Yellow
        if ($PSCmdlet.ShouldProcess('PowerShell install script', 'Download and run')) {
            try {
                $installScript = Invoke-RestMethod -Uri 'https://aka.ms/install-powershell.sh' -ErrorAction Stop
                $tempSh = [System.IO.Path]::GetTempFileName() + '.sh'
                Set-Content -Path $tempSh -Value $installScript -Encoding UTF8
                Write-Host "  Install script saved to: $tempSh" -ForegroundColor Cyan
                Write-Host "  Run:  bash $tempSh -stable" -ForegroundColor Cyan
            } catch {
                Write-Warning "  Could not download install script: $($_.Exception.Message)"
            }
        }
    } else {
        Write-Host "  Windows (no winget): downloading MSI installer from GitHub..." -ForegroundColor Yellow
        if ($PSCmdlet.ShouldProcess('PowerShell MSI', 'Download')) {
            try {
                $releases = Invoke-RestMethod -Uri 'https://api.github.com/repos/PowerShell/PowerShell/releases/latest' -UseBasicParsing -ErrorAction Stop
                $msiAsset = $releases.assets | Where-Object { $_.name -match 'win-x64\.msi$' } | Select-Object -First 1
                if ($msiAsset) {
                    $msiPath = Join-Path $env:TEMP $msiAsset.name
                    Invoke-WebRequest -Uri $msiAsset.browser_download_url -OutFile $msiPath -UseBasicParsing -ErrorAction Stop
                    Write-Host "  Downloaded: $msiPath" -ForegroundColor Green
                    Write-Host "  Run the MSI to complete installation." -ForegroundColor Cyan
                    Start-Process $msiPath
                } else {
                    Write-Warning "  Could not find MSI asset in latest release."
                }
            } catch {
                Write-Warning "  Download failed: $($_.Exception.Message)"
            }
        }
    }
}

Update-PowerShellVersion

'@)

# --- Section 3: Latest .NET SDK ---
[void]$sb.AppendLine(@'

# ════════════════════════════════════════════════════════════════════
# SECTION 3 -- LATEST .NET SDK
# ════════════════════════════════════════════════════════════════════
Write-Host ''
Write-Host '── Section 3: .NET SDK ──' -ForegroundColor Yellow
Write-Host ''

function Update-DotNetSdk {
    $dotnetCmd = Get-Command dotnet -ErrorAction SilentlyContinue
    if ($dotnetCmd) {
        $dotnetVer = & dotnet --version 2>&1
        Write-Host "  Current .NET SDK: $dotnetVer" -ForegroundColor Cyan
    } else {
        Write-Host "  .NET SDK not found on this machine." -ForegroundColor Red
    }

    $hasWinget = $null -ne (Get-Command winget -ErrorAction SilentlyContinue)

    if ($hasWinget) {
        Write-Host "  Checking winget for latest .NET SDK..." -ForegroundColor DarkGray
        try {
            if ($PSCmdlet.ShouldProcess('.NET SDK (winget)', 'Install/Upgrade')) {
                $result = winget upgrade --id Microsoft.DotNet.SDK.9 --source winget --accept-source-agreements --accept-package-agreements 2>&1 | Out-String
                if ($result -match 'No applicable update found') {
                    # Try install instead
                    winget install --id Microsoft.DotNet.SDK.9 --source winget --accept-source-agreements --accept-package-agreements 2>&1 | Out-String | Out-Null
                }
                Write-Host "  .NET SDK install/upgrade initiated via winget." -ForegroundColor Green
            } else {
                Write-Host "  [WhatIf] Would install/upgrade .NET SDK via winget" -ForegroundColor DarkYellow
            }
            return
        } catch {
            Write-Warning "  winget method failed: $($_.Exception.Message)"
        }
    }

    # Fallback: official dotnet-install script
    if ($PSVersionTable.Platform -eq 'Unix') {
        Write-Host "  Downloading dotnet-install.sh..." -ForegroundColor Yellow
        if ($PSCmdlet.ShouldProcess('dotnet-install.sh', 'Download and run')) {
            try {
                $installScript = Invoke-RestMethod -Uri 'https://dot.net/v1/dotnet-install.sh' -ErrorAction Stop
                $tempSh = [System.IO.Path]::GetTempFileName() + '.sh'
                Set-Content -Path $tempSh -Value $installScript -Encoding UTF8
                & bash $tempSh --channel LTS
                Write-Host "  .NET SDK installed." -ForegroundColor Green
            } catch {
                Write-Warning "  Install failed: $($_.Exception.Message)"
            }
        }
    } else {
        Write-Host "  Downloading dotnet-install.ps1..." -ForegroundColor Yellow
        if ($PSCmdlet.ShouldProcess('dotnet-install.ps1', 'Download and run')) {
            try {
                $installScript = Invoke-RestMethod -Uri 'https://dot.net/v1/dotnet-install.ps1' -ErrorAction Stop
                $tempPs1 = Join-Path $env:TEMP 'dotnet-install.ps1'
                Set-Content -Path $tempPs1 -Value $installScript -Encoding UTF8
                & $tempPs1 -Channel LTS
                Write-Host "  .NET SDK installed." -ForegroundColor Green
            } catch {
                Write-Warning "  Install failed: $($_.Exception.Message)"
            }
        }
    }
}

Update-DotNetSdk

'@)

# --- Footer ---
[void]$sb.AppendLine(@'

# ════════════════════════════════════════════════════════════════════
# SUMMARY
# ════════════════════════════════════════════════════════════════════
Write-Host ''
Write-Host '── Complete ──' -ForegroundColor Green
Write-Host ''
Write-Host 'Re-open a new terminal/shell session to pick up any PATH changes.' -ForegroundColor Yellow
Write-Host 'Run this script again with -WhatIf to preview without changes.' -ForegroundColor DarkGray
Write-Host ''
'@)

# ── write the generated script ────────────────────────────────────
Set-Content -Path $outFile -Value $sb.ToString() -Encoding UTF8
Write-Host "Installer script generated: $outFile" -ForegroundColor Green

if ($Open) {
    Start-Process $outFile
}

return $outFile






# --- End lifecycle logging ---
if (Get-Command Write-AppLog -ErrorAction SilentlyContinue) {
    Write-AppLog -Message "Completed: $($MyInvocation.MyCommand.Name)" -Level 'Info'
}
